name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Install modules
        working-directory: ui
        run: pnpm install
      - name: Lint
        working-directory: ui
        run: pnpm run --if-present lint
